//<mdk sortorder = "-100" />
using Sandbox.ModAPI.Ingame;

namespace IngameScript
{
    partial class Program : MyGridProgram
    {
        // Generated by MDK: $MDK_DATETIME$
 //       string sDeploy = "$MDK_DATETIME$";
    }
}
